# Generated by Django 5.2a1 on 2026-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="cover_image_url",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="blog/"),
        ),
    ]
