# Generated by Django 5.2a1 on 2026-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_blogpost_cover_image_url_blogpost_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tagline",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
