# Generated by Django 5.2a1 on 2026-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_tagline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="icon",
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
