# Generated by Django 5.2a1 on 2026-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_servicefeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="About Nestway", max_length=255),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="We are a trusted trucking dispatching company dedicated to helping owner-operators and small fleets thrive."
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(default="Our Mission", max_length=255),
                ),
                (
                    "mission_body",
                    models.TextField(
                        default="To empower truck drivers and fleet owners with reliable dispatching, transparent pay, and the freedom to be home more often."
                    ),
                ),
                (
                    "vision_title",
                    models.CharField(default="Our Vision", max_length=255),
                ),
                (
                    "vision_body",
                    models.TextField(
                        default="A logistics industry where every driver is treated as a partner, not a number."
                    ),
                ),
                (
                    "values_title",
                    models.CharField(default="Our Values", max_length=255),
                ),
                (
                    "values_body",
                    models.TextField(
                        default="Integrity, Transparency, Partnership, Excellence."
                    ),
                ),
                (
                    "ceo_name",
                    models.CharField(default="Khamidjon Odilov", max_length=255),
                ),
                (
                    "ceo_title",
                    models.CharField(default="Founder & CEO", max_length=255),
                ),
                (
                    "ceo_bio",
                    models.TextField(
                        default="With years of hands-on experience in the Eastern US trucking market, Khamidjon founded Nestway to bring transparency and partnership to an industry that needed it most."
                    ),
                ),
                (
                    "ceo_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "team_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "team_section_title",
                    models.CharField(default="Meet Our Team", max_length=255),
                ),
                (
                    "team_section_body",
                    models.TextField(
                        default="A dedicated group of dispatching professionals committed to your success on the road."
                    ),
                ),
                ("stat_1_number", models.CharField(default="500+", max_length=50)),
                (
                    "stat_1_label",
                    models.CharField(default="Owner-Operators Served", max_length=100),
                ),
                ("stat_2_number", models.CharField(default="35%", max_length=50)),
                (
                    "stat_2_label",
                    models.CharField(
                        default="Avg. Deadhead Mile Reduction", max_length=100
                    ),
                ),
                ("stat_3_number", models.CharField(default="98%", max_length=50)),
                (
                    "stat_3_label",
                    models.CharField(default="On-Time Delivery Rate", max_length=100),
                ),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Page",
            },
        ),
    ]
