# Generated by Django 5.2a1 on 2026-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_aboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="stat_4_label",
            field=models.CharField(default="Years of Experience", max_length=100),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="stat_4_number",
            field=models.CharField(default="7+", max_length=50),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="stat_1_label",
            field=models.CharField(
                default="Customer Satisfaction Rate", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="stat_1_number",
            field=models.CharField(default="92%", max_length=50),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="stat_2_label",
            field=models.CharField(default="Partner Companies", max_length=100),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="stat_2_number",
            field=models.CharField(default="30+", max_length=50),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="stat_3_label",
            field=models.CharField(default="Happy Drivers", max_length=100),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="stat_3_number",
            field=models.CharField(default="50+", max_length=50),
        ),
    ]
