# Generated by Django 5.2a1 on 2026-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_aboutpage_stat_4_label_aboutpage_stat_4_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label, e.g. 'Sales Team' or 'Support Mailbox'",
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to temporarily stop sending to this address.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Email",
                "verbose_name_plural": "Notification Emails",
                "ordering": ["label", "email"],
            },
        ),
    ]
