# Generated by Django 5.2a1 on 2026-05-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notificationemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[("article", "Article"), ("success_story", "Success Story")],
                default="article",
                max_length=50,
            ),
        ),
    ]
