# Generated by Django 5.2a1 on 2026-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_create_admin_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/photos/")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption shown on hover.",
                        max_length=255,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "About Photo",
                "verbose_name_plural": "About Photos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(help_text="The driver's testimonial text.")),
                (
                    "author_name",
                    models.CharField(help_text="e.g. Marcus T.", max_length=255),
                ),
                (
                    "author_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 3 years with Nestway",
                        max_length=255,
                    ),
                ),
                (
                    "initials",
                    models.CharField(
                        blank=True,
                        help_text="2–4 letter initials shown in the avatar circle, e.g. MT",
                        max_length=4,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order"],
            },
        ),
    ]
