# Generated by Django 5.2a1 on 2026-05-21 09:01

import django.db.models.deletion
from django.db import migrations, models


def link_existing_about_photos(apps, schema_editor):
    AboutPage = apps.get_model('core', 'AboutPage')
    AboutPhoto = apps.get_model('core', 'AboutPhoto')
    
    # Ensure the singleton AboutPage exists
    about_page, created = AboutPage.objects.get_or_create(pk=1)
    
    # Link all existing photos to the AboutPage singleton
    AboutPhoto.objects.update(about_page=about_page)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_seed_testimonials_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutphoto",
            name="about_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="core.aboutpage",
            ),
        ),
        migrations.RunPython(link_existing_about_photos, reverse_code=migrations.RunPython.noop),
    ]
