# Generated by Django 5.2a1 on 2026-05-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_aboutphoto_about_page"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutPhoto",
        ),
    ]
