# Generated by Django 5.2a1 on 2026-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_delete_aboutphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlead",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
