# Generated by Django 5.2a1 on 2026-05-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_contactlead_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_name",
                    models.CharField(
                        default="award",
                        help_text="Name of icon to display, e.g. 'award', 'shield', 'star', 'truck'",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DriverRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_text", models.CharField(max_length=500)),
                (
                    "driver_type",
                    models.CharField(
                        choices=[
                            ("company", "Company Drivers only"),
                            ("owner_operator", "Owner Operators only"),
                            ("both", "Both categories"),
                        ],
                        default="both",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Driver Requirement",
                "verbose_name_plural": "Driver Requirements",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PartnerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Primary Broker, Major Shipper",
                        max_length=100,
                    ),
                ),
                ("initials", models.CharField(blank=True, max_length=4)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Partner Review",
                "verbose_name_plural": "Partner Reviews",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="USTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="us_team/"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "US Team Member",
                "verbose_name_plural": "US Team Members",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="contactlead",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contactlead",
            name="experience_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contactlead",
            name="lead_type",
            field=models.CharField(
                choices=[
                    ("general", "General Contact"),
                    ("company_driver", "Company Driver Application"),
                    ("owner_operator", "Owner Operator Application"),
                    ("investor", "Truck Investor Program"),
                    ("academy", "Truvision Academy Enrollment"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
