# Generated by Django 5.2a1 on 2026-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_initial_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image_home",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="services/",
                verbose_name="Homepage Image",
            ),
        ),
    ]
