# Generated by Django 5.2a1 on 2026-05-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_service_image_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlead",
            name="lead_type",
            field=models.CharField(
                choices=[
                    ("general", "General Contact"),
                    ("company_driver", "Company Driver"),
                    ("owner_operator", "Owner Operator"),
                    ("company_owner", "Company Owner"),
                    ("investor", "Truck Investor Program"),
                    ("academy", "Truvision Academy Enrollment"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
