# Generated by Django 5.2a1 on 2026-05-25 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_contactlead_lead_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_label",
                    models.CharField(
                        default="Truvision Academy by Nestway", max_length=255
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Learn dispatch. Build a career.", max_length=255
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Train online from anywhere. Real skills, real loads, real income."
                    ),
                ),
                (
                    "course_duration",
                    models.CharField(
                        default="Course duration: 4–6 weeks, fully self-paced",
                        max_length=255,
                    ),
                ),
                ("phone", models.CharField(default="(215) 770-2630", max_length=50)),
                (
                    "email",
                    models.EmailField(default="info@nestway.net", max_length=254),
                ),
            ],
            options={
                "verbose_name": "Academy Page",
                "verbose_name_plural": "Academy Page",
            },
        ),
        migrations.CreateModel(
            name="AcademyModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "academy_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.academypage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Module",
                "verbose_name_plural": "Curriculum Modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AcademyBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "academy_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="core.academypage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academy Benefit",
                "verbose_name_plural": "Academy Benefits",
                "ordering": ["order"],
            },
        ),
    ]
