# Generated by Django 5.2a1 on 2026-05-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_academypage_academymodule_academybenefit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academypage",
            name="hero_title",
            field=models.CharField(
                default="Learn dispatch.<br>Build a career.", max_length=255
            ),
        ),
    ]
