# Generated by Django 5.2a1 on 2026-06-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_academypage_hero_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="us_map_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload your US routing/operations map image here.",
                null=True,
                upload_to="about/",
                verbose_name="US Operations Map",
            ),
        ),
    ]
