# Generated by Django 5.2a1 on 2026-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_us_map_image_to_aboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number (e.g. +1234567890 or 1234567890). Leave blank to hide the WhatsApp floating button.",
                max_length=50,
            ),
        ),
    ]
